name: Build Docker for Android

on:
  push:
    tags:
      - "*"
  
permissions:
  contents: write
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Checkout Termux Code
      uses: actions/checkout@v4
      with:
        repository: termux/termux-packages
        fetch-depth: 1
        path: termux-packages
    
    - name: Build Docker
      run: |
        cd termux-packages
        patch -p1 < ../docker.patch
        ./scripts/run-docker.sh ./build-package.sh docker docker-compose
        cd output
        bash $GITHUB_WORKSPACE/package_docker.sh
        mv docker.tar.xz $GITHUB_WORKSPACE/module/docker.tar.xz
    
    - name: Update repository
      run: |
        # Store the version info to environment variables
        versionString="${{ env.GITHUB_REF }}"

        IFS='.' read -ra VERSION_PARTS <<< "${versionString//[^0-9.]/}" # Get numeric version parts
        newVersionCode=$(printf "%02d%02d%02d%02d" "${VERSION_PARTS[0]}" "${VERSION_PARTS[1]}" "${VERSION_PARTS[2]}" "${VERSION_PARTS[3]}") # Get version code number

        # Update module.prop
        sed -i "s/^version=.*/version=${versionString}/" module.prop
        sed -i "s/^versionCode=.*/versionCode=$newVersionCode/" module.prop
        git add .

    - name: Commit and push
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        if git diff --staged --quiet; then
          echo "No changes to commit"
        else
          git commit -m "Updated to ${{ env.GITHUB_REF }}"
          git push
        fi
  
    - name: Create Module
      run: |
        cd module
        zip -9 -r "$GITHUB_WORKSPACE/Magisk-Dockerd-${{ env.GITHUB_REF }}}.zip" ./

    - name: Create Release
      id: create_release
      uses: softprops/action-gh-release@v2
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        append_body: true
        generate_release_notes: true
        make_latest: true
        files: |
          ./Magisk-Dockerd-${{ env.GITHUB_REF }}}.zip
        name: Dockerd ${{ env.GITHUB_REF }}}
        tag_name: ${{ env.GITHUB_REF }}

